name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle # or app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: 1.0.0
      - name: Build the app
        run: ./gradlew clean assembleDebug
      - name: Upload build to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: VladSpreys/Sleep-Tracker
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Public
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: false
      - name: Successful Discord notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: |
            "Sleep Tracker ${{github.run_number}} has been released"
            "[Download](https://install.appcenter.ms/users/vladspreys/apps/sleep-tracker/distribution_groups/public)
      - name: Failed Discord notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "The application build failed"
