name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle # or app/build.gradle.kts
          versionCode: ${{github.run_number}}
      - name: Expose version name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          expose-version-name: 'true'
          expose-version-code: 'true'
      - name: Run ktlint
        run: ./gradlew ktlintCheck
      - name: Build the app
        run: ./gradlew clean assembleDebug
      - name: Upload build to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: VladSpreys/Sleep-Tracker
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Public
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: false
      - name: Successful Discord notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          avatar_url: ${{ secrets.DISCORD_AVATAR_URL }}
          description: |
            Sleep Tracker ${{env.ANDROID_VERSION_NAME}} (${{env.ANDROID_VERSION_CODE}}) has been released.
            [Download](${{secrets.APP_CENTER_PUBLIC_URL}})
      - name: Failed Discord notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          avatar_url: ${{ secrets.DISCORD_AVATAR_URL }}
          description: |
            Sleep Tracker ${{env.ANDROID_VERSION_NAME}} (${{env.ANDROID_VERSION_CODE}}) build failed.
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
